name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag ghcr.io/mrswaggerr/docker-signal-desktop:latest
    - name: login
      env: # Or as an environment variable
        super_secret: ${{ secrets.SECRET_TOKEN }}
      run: echo $CR_PAT | docker login ghcr.io -u MrSwaggerr --password-stdin
    - name: push docker
      run: docker push ghcr.io/mrswaggerr/docker-signal-desktop:latest
